yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
# импорт include позволит использовать адреса, включенные в приложения
from django.urls import include, path

urlpatterns = [
    path('', include(('posts.urls', 'posts'), namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField()
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )

    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name='posts'
        )

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


def index(request):
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html> 
<html lang="ru">          
  <head>       
  </head>
  <body>       
    <header>
      {% load static %}
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"
      {% include 'includes/header.html' %}
    </header>
    <main>
      <h1> {{text }} </h1>
      {% block content %}
        Контент не подвезли :(
      {% endblock %}
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %} 
    </footer>
  </body>
</html>

yatube/templates/includes/footer.html
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
    <p>© 2023 Copyright <a href="{% url 'posts:index' %}">
     <span style="color:red">Ya</span>tube </a> </p> 

yatube/templates/includes/header.html
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->    
    {% load static %}
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index' %}">
          <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube
        </a>
      </div>
    </nav> 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
<!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1>{{group.title}}</h1>
        <p>
          {{group.description}}
        </p>
          {% for post in posts %}
          <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>  
      </article>  
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
      </div> 
      {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container py-5">     
        <h1>Последние обновления на сайте</h1>
        {% for post in posts %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
        <p>{{ post.text }}</p>    
        {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %} 
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 
      </div>  
      {% endblock %}